name: cd

on:
  workflow_run:
    workflows: ["ci"]
    branches: [master]
    types: 
      - completed

jobs:
 deploy:
    strategy:
      matrix:
        environemt: [qa, prod]

    name: Deploy ${{ matrix.environemt }}

    environment: ${{ matrix.environemt }}

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: List
        run: |
          ls -la
          ls -la build/

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.BUCKET }}
