name: ci-cd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build & run Tests

    runs-on: ubuntu-latest

    steps:
    - name: Check artifacts exists
      run: |
        ARITIFACTS=`curl -s \
          --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
          | jq .artifacts \
          | jq -c 'map(select(.name | contains("${{ github.sha }}")))'`

        echo "$ARITIFACTS"

        if [[ $ARITIFACTS != "\[\]" ]]; then
          echo "echo "::set-output name=artifacts_exist::True"
        else
          echo "echo "::set-output name=artifacts_exist::False"
        fi
        
    - run: mkdir build
    - run: echo "cdf" > build/test.txt

    - run: |
        echo "$ABC"
        echo "CDF"
      shell: bash
      env:
        ABC: ${{ secrets.ABC }}
        CDF: ${{ secrets.CDF }}

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
          name: ${{ github.sha }}
          path: build/

  deploy-qa:
    name: Deploy QA

    runs-on: ubuntu-latest

    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - run: |
          echo "$ABC"
          echo "$CDF"
        shell: bash
        env:
          ABC: ${{ secrets.ABC }}
          CDF: ${{ secrets.CDF }}

      - name: List
        run: |
          ls -la
          ls -la build/

      - name: Deploy static site to S3 bucket
        run: aws s3 sync --delete --cache-control max-age=604800 ./build/ s3://${{ secrets.BUCKET }}
