name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build & run Tests

    runs-on: ubuntu-latest

    steps:
    - run: mkdir build
    - run: echo "cdf" > build/test.txt

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
          name: build
          path: build/
